function noreturn=fwin(arg1, arg2, arg3);
% fwin :  This program handles graph interface for fractal - an ATLAST
%   workshop project: 2D/3D Fractal Pictures of Fern and Other Fractal Images!
% This project is developed by: Victor, Daniel, Henry, Herb, Zhang
%   written by -- szhang@math.udel.edu
% Created: 7/1997
% Last modification: 9/2002

global sli_1 sli_1cur sli_2 sli_2cur fig cb_box popcol cpop tf np nv cm
global edp x pct figa

se='Style'; sg='String'; pn='Position'; ck='CallBack';ve='Value';
ut='Unit'; nd='normalized'; 
 
if (arg1 == 1 ),
  figa=figure('MenuBar', 'none', 'NumberTitle','off',...
   'Name', 'ATLAST Project: Fractal (pop-up window)',...
   'Units', 'normalized'); clf(figa);
  uicontrol(figa, se,'text',ut,nd,pn,[0.05 0.05 0.9 0.9],...
      sg, { ' ',' ',...
           ' ATLAST Workshop Project ', ' ', ...
            ' Madison, Wisconsin -- August, 1997 ', ' ',' ',...
           'Herbert C. Lyon, Black Hawk College',...
           'Daniel Okunbor, University of Missouri-Rolla',...
           'Victor Piotrowski, University of Wisconsin-Superior',...
           'Henry J. Ricardo, Medgar Evers College(CUNY)',...
           'Shangyou S. Zhang, University of Delaware', ' ',' ',...
           'Copyright ATLAST Team, 1997, 2002',' ',' ', ' ',' ',...
           'This Matlab programs applies linear and affine transformations to generate fractal images of some natural objects.  For more information, please read  ATLAST Computer Exercises for Linear Algebra, 2nd ed., or contact Shangyou Zhang at szhang@udel.edu.                               ',...
           ' ',...
             ' '},...
           'BackgroundColor',[0.9 0.9 1.0]);
  uicontrol(figa,se,'push',ut,nd,pn,[0.4 0.06 .2 .05], ...
        sg,'Done',ck,'close(figa)');

end
if (arg1 == 2 ),
  figa=figure('MenuBar', 'none', 'NumberTitle','off',...
   'Name', 'ATLAST Project: Fractal (pop-up window)',...
   'Units', 'normalized'); clf(figa);
  uicontrol(figa, se,'text',ut,nd,pn,[0.05 0.05 0.9 0.9],...
      sg, { ' ',' Affine Transformation ', ' ', ...
            ' [ u ]     [ a     b ] [ x ]      [ e ] ',...
            ' [     ] = [           ] [    ]  +  [    ] ',...
            ' [ v ]     [ c     d ] [ y ]      [ f ] ', ' ',' ',...
            'An affine transformation is a combination of a linear transformation and a translation.   The linear transformations, represented by 2x2 matrices, are rotations and contractions. Combining these with translations,  we have the necessary tools to produce fractal images.                                    ',' ',' ',...
         'First, we define a basic graph so that Matlab can plot some points. Then on the next level, we apply affine transformations and produce many copies of the same graph, but of smaller size, of different orientation, and at different locations.  After combining several levels of such graphs,  we get the final fractal image.                                   ',...
             ' '},...
           'BackgroundColor',[0.9 1.0 0.9]);
  uicontrol(figa,se,'push',ut,nd,pn,[0.4 0.06 .2 .05], ...
        sg,'Done',ck,'close(figa)');

end
if (arg1 == 3 ),
  figa=figure('MenuBar', 'none', 'NumberTitle','off',...
   'Name', 'ATLAST Project: Fractal (pop-up window)',...
   'Units', 'normalized'); clf(figa);
  uicontrol(figa, se,'text',ut,nd,pn,[0.05 0.05 0.9 0.9],...
      sg, { ' ','  ', ' ', ' ','  ', ' ',...
            ' Please contact Shangyou Scott Zhang at ', ' ',...
            ' szhang@udel.edu '},...
           'BackgroundColor',[0.1 0.9 0.9]);
  uicontrol(figa,se,'push',ut,nd,pn,[0.4 0.06 .2 .05], ...
        sg,'Done',ck,'close(figa)');

end

if (arg1 == 41 ),
  figa=figure('MenuBar', 'none', 'NumberTitle','off',...
   'Name', 'ATLAST Project: Fractal (pop-up window)',...
   'Units', 'normalized'); clf(figa);
  uicontrol(figa, se,'text',ut,nd,pn,[0.05 0.05 0.9 0.9],...
      sg, { ' ','Type fractal from a Matlab prompt.                                                                                              ', ' ', 'We can choose color by clicking    Color    menu.                                                   ','  ', ...
            'We can select different   Demo   number to get different fractals                                        ', ' ',...
            'We can center the graph by click mouse at the point where we want it centered                                            ', ' ',...
            'We can click    Zoom In/Out   to view details or whole graph                                              ', ' ',...
            'We can select the levels of graphs to be combined, and the number of points for each level graph.                                              ', ' ',...
            'We can define our own graph by modify the matrix  tf in the brown text window                                              ', ' ',...
            'We can define our own graph by modify the matrix  tf in the brown text window                                              ', ' ',...
            '  '},...
           'BackgroundColor',[0.1 0.9 0.9]);
  uicontrol(figa,se,'push',ut,nd,pn,[0.3 0.06 .2 .05], ...
        sg,'More',ck,'fwin(41)');
  uicontrol(figa,se,'push',ut,nd,pn,[0.5 0.06 .2 .05], ...
        sg,'Done',ck,'close(figa)');
  text(0.1, 0.9, 'Type f from a Matlab prompt');
  text(0.1, 0.85, 'Select a color by clicking    Color    menu');

end
if (arg1 == 4 ),
  figa=figure('MenuBar', 'none', 'NumberTitle','off',...
   'Name', 'ATLAST Project: Fractal (pop-up window)',...
   'Units', 'normalized'); clf(figa);
  uicontrol(figa,se,'push',ut,nd,pn,[0.4 0.06 .2 .05], ...
        sg,'Done',ck,'close(figa)');
  text(0.1, 0.9, '1 From a Matlab prompt type: fractal');
  text(0.1, 0.85, '2 Select a color by clicking Color menu.');
  text(0.1, 0.80, '3 Select a Demo number to get different fractals.');
  text(0.1, 0.75, '4 Center the graph by clicking the mouse at the point where you want the center to be.');
  text(0.1, 0.70, '5 Click Zoom In/Out to view details or the whole graph.');
  text(0.1, 0.65, '6 Select the number of levels of graphs to be combined.');
  text(0.1, 0.60, '7 Select the number of points for each level graph.');
  text(0.1, 0.55, '8 Modify if you wish the tf matrix in the brown text widow.');
  text(0.1, 0.50, '  (This would generate different fractals.) ');
  text(0.1, 0.40, '9 Click plot now to replot the graph.');

  axis off
end
